- hosts: localhost
  become: yes
  vars:
    target_service: httpd
  tasks:
    - name: Install software
      block:
        - name: Start service
          service:
            name: "{{ target_service }}"
            state: started
          register: service_status
      rescue:
        - name: Debug service status
          debug:
            var: service_status
      always:
        - name: Ensure service status check was run
          debug:
            msg: "Tried to ensure service was running"

