---
- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: Karthik@123
  tasks:
    - name: install software
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - elinks
        - nmap
        - ncat
        - bind

