---
- name: File Module
  hosts: all

  tasks:
  - name: Creating a file
    file:
      path: /tmp/newfile.txt
      state: absent
      owner: karthik
      group: karthik
      mode: 700

  - name: Creating a directory
    file:
      path: /tmp/myfolder
      state: absent
