# ---
# - hosts: web
#   become: true
#   become_method: sudo
#   tasks:
#     - name: Create a new user
#       user:
#         name: naren
#         state: present
#         shell: /bin/bash
# 
#     - name: Backup the existing /etc/sudoers file
#       copy:
#         src: /etc/sudoers
#         dest: /etc/sudoers.bak
#         owner: root
#         group: root
#         mode: '0644'
# 
#     - name: Add user to /etc/sudoers with NOPASSWD
#       lineinfile:
#         path: /etc/sudoers
#         line: "naren ALL=(ALL) NOPASSWD:ALL"
#         state: present
#         validate: "visudo -cf %s"
---
- hosts: web
  become: yes
  tasks:
    - name: Create a new user
      user:
        name: sudheer
        state: present
        shell: /bin/bash

    - name: Backup the existing /etc/sudoers file
      command: cp /etc/sudoers /etc/sudoers.bak
      notify: Validate sudoers file

    - name: Add user to /etc/sudoers with NOPASSWD
      lineinfile:
        path: /etc/sudoers
        line: "sudheer ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: "visudo -cf %s"

  handlers:
    - name: Validate sudoers file
      command: visudo -c -f /etc/sudoers
      become: yes

